### ISSUE TITLE
Create a docker image from devel branch

### ISSUE THREAD

**Issue by gael-seroul** [3dem/emhub#113]
Hi,
I can create a docker image with the latest image (1.0.2). I tried to create a docker image from the devel branch:

Dockerfile:
```
FROM python:3.8
LABEL description="Python 3.8 based image to run emhub application"
LABEL maintainer="J.M. de la Rosa Trevin delarosatrevin@gmail.com"
RUN pip install emhub
ENV EMHUB_INSTANCE /emhub-data
USER nobody
CMD [ "gunicorn", "-k", "gevent", "--workers=2", "emhub:create_app()", "--bind", "0.0.0.0:8080" ]
```

Run build command:
`docker build . -t emhub:gael --no-cache`

Start using docker compose file:
```
version: '3.3'

name: emhub

services:
    cryoEM:
        container_name: 'emhub-gael'
        image: emhub:gael
        restart: unless-stopped
        ports:
            - "8899:8080"
        volumes:
            - /home/crims/cryoEM/emhub-data-dev/:/emhub-data
```

EMHUB is running but the version shown at the bottom is still 1.0.2, from emhub directory if I run
`gunicorn -k gevent --workers=2 'emhub:create_app()' --bind 0.0.0.0:8899`
EMHUB is the right dev version (1.0.4rc2)

I guess this is coming from the command pip install emhub in Dockerfile, do you have any advice to create a docker image using devel branch ?
